### ISSUE TITLE
Last version for win xp

### ISSUE THREAD

**Issue by Dimsok** [paginagmbh/EPUB-Checker#82]
Which is last version for Windows XP?

**Comment by br-pagina** [comment]
Hey, we currently do not have a Windows XP system here for testing this since XP has been outdated for some years now. The key prerequisite is to have Java installed on the system (1.8 Update 91 or higher), since the EPUBChecker essentially is a Java application. Due to the lack of a testing environment we can only make guesses here, but probably if this prerequisite is fulfilled it might even work under Windows XP.
