### ISSUE TITLE
Corrupt File Warning?

### ISSUE THREAD

**Issue by b-t-k** [paginagmbh/EPUB-Checker#89]
I tried to install on a brand new Macbook and it won't open the file. Tried several times.
Version 2.0.9_c023a
Macbook Pro M2 Pro
Ventura 13.4 

Won't open:
![Screenshot 2023-06-19 at 7 55 35 AM](https://github.com/paginagmbh/EPUB-Checker/assets/45247934/f45ab7f6-ace2-436e-8cc6-540adeb35a5e)

**note** just checked it on my Mac Mini 2019 and it is corrupt there too.

**Comment by br-pagina** [comment]
We can replicate the issue and are working on a solution. Thank you for reporting this problem.

**Comment by br-pagina** [comment]
@b-t-k we uploaded a new version of the appplication with which the problems are solved on our Mac systems. Could you please try and download the new version? Note: you need to do a hard refresh of the page, otherwise the old version might still be downloaded. Here is the link: https://pagina.gmbh/startseite/leistungen/publishing-softwareloesungen/epub-checker/

**Comment by b-t-k** [comment]
Works great. Thanks!
